LESSAOSP_BUILD_TYPE ?= UNOFFICIAL

# LESSAOSP Props
LESSAOSP_BASE_VERSION = 2.0
LESSAOSP_CODENAME := Tigris

# LOSP Props
LESSAOSP_BASE_VERSION = 2.0
LESSAOSP_CODENAME := Tigris

CUSTOM_DATE_YEAR := $(shell date -u +%Y)
CUSTOM_DATE_MONTH := $(shell date -u +%m)
CUSTOM_DATE_DAY := $(shell date -u +%d)
CUSTOM_DATE_HOUR := $(shell date -u +%H)
CUSTOM_DATE_MINUTE := $(shell date -u +%M)
CUSTOM_BUILD_DATE_UTC := $(shell date -d '$(CUSTOM_DATE_YEAR)-$(CUSTOM_DATE_MONTH)-$(CUSTOM_DATE_DAY) $(CUSTOM_DATE_HOUR):$(CUSTOM_DATE_MINUTE) UTC' +%s)
CUSTOM_BUILD_DATE := $(CUSTOM_DATE_YEAR)$(CUSTOM_DATE_MONTH)$(CUSTOM_DATE_DAY)-$(CUSTOM_DATE_HOUR)$(CUSTOM_DATE_MINUTE)

LESSAOSP_PLATFORM_VERSION := 13.0

CUSTOM_VERSION := LessAOSP_$(LESSAOSP_BASE_VERSION)-BETA_$(CUSTOM_BUILD)-$(LESSAOSP_PLATFORM_VERSION)-$(CUSTOM_BUILD_DATE)-$(LESSAOSP_BUILD_TYPE)
LESSAOSP_VERSION_PROP := $(LESSAOSP_BASE_VERSION) - BETA
